### ISSUE TITLE
Add new Kourend & Kebos Achievement Diary to OSRSHelper

### ISSUE THREAD

**Issue by DiskImage** [OSRSHelper/OSRSHelper#60]
OSRSHelper has become outdated with the release of the new Kourend & Kebos Lowlands diary on 2019-01-10. 

Diary information: https://oldschool.runescape.wiki/w/Kourend_%26_Kebos_Diary

**Comment by TyMarc** [comment]
@DiskImage Are you talking about the World map?

**Comment by DiskImage** [comment]
> @DiskImage Are you talking about the World map?

No, sorry. My mistake, I thought this was the repo for the extraordinarily helpful diary calculator website, osrshelper.com. apparently that site was abandoned since the Kebos Lowlands were released, rather than updated. None of the existing alternatives even come within a mile of how nice that site's UX was. :/

You can close this.
