### ISSUE TITLE
API end point down"Buying-GF.com" wont resolve get or post any more

### ISSUE THREAD

**Issue by JayBuckley7** [OSRSHelper/OSRSHelper#61]
I use this project as a widget for my home screen and I really like it so I switched the endpoint up to Jagex and parsed the high score csv on my branch.

Will you be bringing your API endpoint back online? If not or if you don't have time I may completely recode the API class to bring back the rest of the functionality.

**Comment by ldionmarcil** [comment]
Everything is up and running again!
