### ISSUE TITLE
Screenshots for F-Droid

### ISSUE THREAD

**Issue by Korb** [OSRSHelper/OSRSHelper#69]
Without a preview, only by a text description, it is difficult to decide whether to download and install the application or not. I propose to add a few screenshots that most fully describe the appearance and functionality of the application. With pictures OSRS Helper will be able to be shown on the [f-droid.org/en/packages/](https://f-droid.org/en/packages/) and on the main page of the f-droid app. More people will be able to see and find OSRS Helper.

https://f-droid.org/en/packages/com.infonuascape.osrshelper/

**Comment by TyMarc** [comment]
We've never published the application on f-droid, and the latest version on that page is 7 years old, it's probably not working anymore

**Comment by Korb** [comment]
> the latest version on that page is 7 years old

https://play.google.com/store/apps/details?id=com.infonuascape.osrshelper —

> Updated on 3 Feb **2023**

What is stopping you as a FOSS application developer from submitting your application to the largest FOSS application repository?
